name: Manually with report

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test to run'
        # Default value if no value is explicitly provided
        default: 'All'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow will execute a robot test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Pip install robotframework
      run: pip install robotframework

    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Show working directory
      run: pwd

    - name: List directory
      run: ls -la

    - name: Execute robot test
      run: robot keyword_driven.robot


    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports
